### ISSUE TITLE
Logo Hikvision in integration

### ISSUE THREAD

**Issue by pepsonEL** [tomasbedrich/home-assistant-hikconnect#10] opened 2021-10-04 07:18 UTC
Hi logo is still not visible.... Only show logo when search integration... But when installed it adn then go to Configuration>integration there is no logo
![135728559-02e2d0a4-fb8f-4617-aa1e-e8fce1624199](https://user-images.githubusercontent.com/71824185/135809304-de915234-773d-4a6b-9277-f7327f4c1078.jpg)

![135728572-13469b16-c389-4fc9-ba6a-492022405012](https://user-images.githubusercontent.com/71824185/135809319-e7ea4832-8236-4a2f-a6f7-aa5790fdb941.jpg)

**Comment by tomasbedrich** [comment] 2021-10-04 07:33
Duplicate of #3.

**Closed by tomasbedrich** 2021-10-04 07:33 UTC

**Comment by pepsonEL** [comment] 2021-10-04 07:36
Yes but #3 was closed but it still no working.
