### ISSUE TITLE
Limited number of cameras

### ISSUE THREAD

**Issue by BrianMay-pt** [tomasbedrich/home-assistant-hikconnect#19] opened 2022-01-24 12:42 UTC
Hi,
So this is working with 7 of my 8 cameras, but that last one appears in the entities list of the integration, but then it doesn't appear listed when you try to add it to a card, all other 7 are ok.
Is this an integrations or homeassistant issue? it's always the same one as I have tried to add and remove the integration a couple of times (it's live in the app)
Also, there's on of the cameras that is live on app but not in homeassistant.

Cheers,

**Comment by BrianMay-pt** [comment] 2022-01-24 12:42
P.S. great job, by the way!kudos

**Comment by tomasbedrich** [comment] 2022-01-25 23:21
Hi @BrianMay-pt, I've just recently updated README, please read it carefully, especially the Overview section.

After you do that, can you please clarify your issue? Are you referring to 7/8 channels + **locks connected** to each of them? Or are you referring to live camera stream (which would be duplicate of #6)?

**Comment by BrianMay-pt** [comment] 2022-01-26 16:04
Hi @tomasbedrich it's live ip camera stream. It works, but I can't add a live view card for one of them. Also, they don't appear in google home if using nabucasa

**Comment by tomasbedrich** [comment] 2022-01-31 23:03
Brian, as mentioned in issue #6, there is no camera live view implemented yet in this integration. As a direct consequence, it is pointless to discuss whether a live stream appear in Google Home using Nabu Casa. So what exactly do you mean by "this is working with ... my cameras"? 

My attention was attracted by another thing: you mentioned there is some cutoff/limit in number of cameras – i.e. 7 out of 8 are working. That would be legitimate bug to discuss.

To clarify things a little bit, could you please provide screenshots from:

1. your Hik-Connect app,
2. all Home Assistant entities created by this integration?

**Comment by silvatyrant** [comment] 2022-03-01 16:40
@BrianMay-pt per @tomasbedrich, what do you mean by "this is working"? Do you have a live view?

**Comment by tomasbedrich** [comment] 2023-09-02 09:20
Stale / invalid.

**Closed by tomasbedrich** 2023-09-02 09:20 UTC
